### ISSUE TITLE
Create a Symbolic Link  by scoop

### ISSUE THREAD

**Issue by Befod** [borger/scoop-galaxy-integrations#1]
use these [properties](https://github.com/lukesampson/scoop/wiki/App-Manifests):
`"depends": "sudo",` :run as administrator
`post_install`: A one-line string, or array of strings, of the commands to be executed after an application is installed.Or `installer` and `uninstaller`

**Comment by borger** [comment]
Hello @Befod ,
Thank you for your suggestion.
Good point, I'll experiment a bit, and push it to the repo.

**Comment by borger** [comment]
I've created a dev branch to test out this feature, as of now, I've implemented it only for battlenet, I've done a few tests and fixes, all seems good, I'll be testing some more and implement for the remaining integrations. Feel free to test, let me know if you have any issues or recommendations.

**Comment by borger** [comment]
Hello @Befod,

Developed and pushed to the main branch. Thank you for your suggestion!
