### ISSUE TITLE
Amazon Gaming (replaces Twitch)

### ISSUE THREAD

**Issue by SarcevicAntonio** [borger/scoop-galaxy-integrations#14]
Twitch for Windows 10 no longer supports installing games.
There is an Amazon Plugin on awesome-gog which works fine that could be added

**Comment by borger** [comment]
Hello @SarcevicAntonio,

Thanks for the heads up! I was not aware of the change. I've updated the repository to use the amazon integration instead. You can install it by: `scoop install galaxy-amazon`
