### ISSUE TITLE
galaxy-rockstar@0.3.3: hash check failed

### ISSUE THREAD

**Issue by tsuki-simp** [borger/scoop-galaxy-integrations#6]
I'm not entire sure what happened but I am unable to update. It just fails out of verifying hash.

> PS C:\WINDOWS\system32> scoop update *
galaxy-rockstar: 0.3.1 -> 0.3.3
Updating one outdated app:
Updating 'galaxy-rockstar' (0.3.1 -> 0.3.3)
Downloading new version
windows.zip (1.4 MB) [========================================================================================] 100%
Checking hash of windows.zip ... ERROR Hash check failed!
App:         galaxy-integrations/galaxy-rockstar
URL:         https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/releases/download/0.3.3/windows.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    e5bfe47881dedd56f0fdac4e052b39944d6ebb350e0220134cf213274200cb47
Actual:      eafb176350b8e90141ffc6bca3222311981c1074a5d515f7321f551a1744ba18

If there is a way to get around this on my end rather than to wait until it's corrected that would be great.

**Comment by borger** [comment]
Hi @scaryred24 apparently there was a new build but using the same version tag, this issue is fixed now, just do a `scoop update` and then `scoop update galaxy-rockstar` if it still doesn't work for you, please run `scoop cache rm *` to clear your cache. Let me know if it works!

**Comment by tsuki-simp** [comment]
Alright it now works. I purge the cache first before pulling from the repo just to make sure that everything has been properly cleaned out before I run an update again. Thank you for addressing the issue.
